### ISSUE TITLE
未翻开的牌可以跟着连起来的牌一起拖走

### ISSUE THREAD

**Issue by orzFly** [Bai-Jie/CardGame#9]
比如：
未翻开的7
翻开的6
翻开的5
翻开的4

可以直接拖动未翻开的7带走这四张牌……

**Comment by orzFly** [comment]
落下这堆牌的时候崩溃啦。
```
PHONE_MODEL=ONEPLUS A3010
BRAND=OnePlus
APP_VERSION_NAME=1.0
CUSTOM_DATA=
STACK_TRACE=rx.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'void gq.baijie.cardgame.client.android.ui.view.AndroidCardView.setOpen(boolean)' on a null object reference
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:205)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
	at rx.internal.operators.OperatorCast$CastSubscriber.onNext(OperatorCast.java:69)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:225)
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:113)
	at gq.baijie.cardgame.business.SpiderSolitaire$State$1.call(SpiderSolitaire.java:318)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
	at gq.baijie.cardgame.business.SpiderSolitaire$State.nextEvent(SpiderSolitaire.java:315)
	at gq.baijie.cardgame.business.SpiderSolitaire$State.move(SpiderSolitaire.java:367)
	at gq.baijie.cardgame.business.SpiderSolitaire.move(SpiderSolitaire.java:227)
	at gq.baijie.cardgame.facade.presenter.SpiderSolitairePresenter.moveCards(SpiderSolitairePresenter.java:177)
	at gq.baijie.cardgame.client.android.ui.view.AndroidSpiderSolitaireView.lambda$null$18(AndroidSpiderSolitaireView.java:600)
	at gq.baijie.cardgame.client.android.ui.view.AndroidSpiderSolitaireView.access$lambda$23(Unknown Source:0)
	at gq.baijie.cardgame.client.android.ui.view.AndroidSpiderSolitaireView$$Lambda$24.call(Unknown Source:4)
	at rx.Completable$26.onCompleted(Completable.java:1926)
	at rx.Completable$10$1.onCompleted(Completable.java:559)
	at rx.internal.operators.OperatorPublish$PublishSubscriber.checkTerminated(OperatorPublish.java:426)
	at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:508)
	at rx.internal.operators.OperatorPublish$PublishSubscriber.onCompleted(OperatorPublish.java:308)
	at gq.baijie.cardgame.client.android.ui.view.AndroidSpiderSolitaireView$OperatorCompleteAfterLastActionDragEndedEvent$1$$Lambda$1.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6499)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void gq.baijie.cardgame.client.android.ui.view.AndroidCardView.setOpen(boolean)' on a null object reference
	at gq.baijie.cardgame.client.android.ui.view.AndroidSpiderSolitaireView.updateOpenIndex(AndroidSpiderSolitaireView.java:400)
	at gq.baijie.cardgame.facade.presenter.SpiderSolitairePresenter$4.call(SpiderSolitairePresenter.java:83)
	at gq.baijie.cardgame.facade.presenter.SpiderSolitairePresenter$4.call(SpiderSolitairePresenter.java:80)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	... 28 more
java.lang.NullPointerException: Attempt to invoke virtual method 'void gq.baijie.cardgame.client.android.ui.view.AndroidCardView.setOpen(boolean)' on a null object reference
	at gq.baijie.cardgame.client.android.ui.view.AndroidSpiderSolitaireView.updateOpenIndex(AndroidSpiderSolitaireView.java:400)
	at gq.baijie.cardgame.facade.presenter.SpiderSolitairePresenter$4.call(SpiderSolitairePresenter.java:83)
	at gq.baijie.cardgame.facade.presenter.SpiderSolitairePresenter$4.call(SpiderSolitairePresenter.java:80)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.OperatorCast$CastSubscriber.onNext(OperatorCast.java:69)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:225)
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:113)
	at gq.baijie.cardgame.business.SpiderSolitaire$State$1.call(SpiderSolitaire.java:318)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
	at gq.baijie.cardgame.business.SpiderSolitaire$State.nextEvent(SpiderSolitaire.java:315)
	at gq.baijie.cardgame.business.SpiderSolitaire$State.move(SpiderSolitaire.java:367)
	at gq.baijie.cardgame.business.SpiderSolitaire.move(SpiderSolitaire.java:227)
	at gq.baijie.cardgame.facade.presenter.SpiderSolitairePresenter.moveCards(SpiderSolitairePresenter.java:177)
	at gq.baijie.cardgame.client.android.ui.view.AndroidSpiderSolitaireView.lambda$null$18(AndroidSpiderSolitaireView.java:600)
	at gq.baijie.cardgame.client.android.ui.view.AndroidSpiderSolitaireView.access$lambda$23(Unknown Source:0)
	at gq.baijie.cardgame.client.android.ui.view.AndroidSpiderSolitaireView$$Lambda$24.call(Unknown Source:4)
	at rx.Completable$26.onCompleted(Completable.java:1926)
	at rx.Completable$10$1.onCompleted(Completable.java:559)
	at rx.internal.operators.OperatorPublish$PublishSubscriber.checkTerminated(OperatorPublish.java:426)
	at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:508)
	at rx.internal.operators.OperatorPublish$PublishSubscriber.onCompleted(OperatorPublish.java:308)
	at gq.baijie.cardgame.client.android.ui.view.AndroidSpiderSolitaireView$OperatorCompleteAfterLastActionDragEndedEvent$1$$Lambda$1.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6499)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

USER_COMMENT=
ANDROID_VERSION=8.1.0
```

**Comment by bai-jie** [comment]
感谢

我找下原因
